#!/usr/bin/env node

/**
 * blueprint-lookup.js
 *
 * Deterministic blueprint lookup. Reads ONLY the programmatic JSON index
 * (blueprints/blueprint-index.json) — never parses the human-facing
 * INDEX.md. YAML blueprints are the source of truth; the JSON index is a
 * fast-loading projection of them, regenerated by scripts/generate-readmes.js.
 *
 * Usage:
 *   node scripts/blueprint-lookup.js <feature-name-or-alias>
 *
 * Behavior:
 *   - Hit by canonical feature name   → prints JSON to stdout, exit 0
 *     (matched_via: "name")
 *   - Hit by alias (e.g. "sign in")   → resolves alias to canonical feature,
 *                                       prints JSON, exit 0
 *                                       (matched_via: "alias", matched_alias: <input>)
 *   - Miss                            → prints message to stderr, exit 1
 *   - Index missing                   → prints remediation to stderr, exit 2
 *
 * JSON shape on hit:
 *   { feature, category, yaml_path, md_path, version, description,
 *     aliases, matched_via, matched_alias? }
 *
 * Normalization: queries are lowercased, trimmed, and separator characters
 * (space, hyphen, underscore) are stripped. So "Sign In", "sign-in",
 * "sign_in", and "signin" all resolve identically.
 */

import { readFileSync, existsSync } from 'fs';
import { dirname, join } from 'path';

const ROOT = dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1'));
const PROJECT_ROOT = join(ROOT, '..');
const INDEX_PATH = join(PROJECT_ROOT, 'blueprints', 'blueprint-index.json');

function fail(msg, code) {
  process.stderr.write(`${msg}\n`);
  process.exit(code);
}

/**
 * Normalize a query or alias for deterministic O(1) matching. MUST stay in
 * sync with normalizeAlias() in scripts/generate-readmes.js and
 * normalizeAliasForCheck() in scripts/validate.js.
 */
function normalize(s) {
  return String(s).toLowerCase().trim().replace(/[\s\-_]+/g, '');
}

function main() {
  const query = process.argv[2];
  if (!query) {
    fail('Usage: node scripts/blueprint-lookup.js <feature-name-or-alias>', 2);
  }

  if (!existsSync(INDEX_PATH)) {
    fail(
      `Programmatic index not found at ${INDEX_PATH}. Run \`npm run generate:readmes\` to build it from the YAML blueprints (they are the source of truth).`,
      2
    );
  }

  let index;
  try {
    index = JSON.parse(readFileSync(INDEX_PATH, 'utf8'));
  } catch (err) {
    fail(
      `Corrupted ${INDEX_PATH} — ${err.message}. Run \`npm run generate:readmes\` to rebuild from YAML.`,
      2
    );
  }

  const features = index.features || {};
  const capabilities = index.capabilities || {};
  const aliasMap = index.alias_map || {};
  const capabilityAliasMap = index.capability_alias_map || {};

  // ─── Pass 1: exact feature-name match ─────────────────────────────────
  const nameHit = features[query] || features[query.toLowerCase()];
  if (nameHit) {
    process.stdout.write(
      JSON.stringify({ ...nameHit, kind: 'feature', matched_via: 'name' }) + '\n'
    );
    return;
  }

  // ─── Pass 2: feature alias lookup (normalized) ────────────────────────
  const normKey = normalize(query);
  const featureCanonical = aliasMap[normKey];
  if (featureCanonical) {
    const hit = features[featureCanonical];
    if (hit) {
      const matchedViaName = normalize(featureCanonical) === normKey;
      const output = {
        ...hit,
        kind: 'feature',
        matched_via: matchedViaName ? 'name' : 'alias',
      };
      if (!matchedViaName) output.matched_alias = query;
      process.stdout.write(JSON.stringify(output) + '\n');
      return;
    }
  }

  // ─── Pass 3: exact capability-name match ──────────────────────────────
  const capHit = capabilities[query] || capabilities[query.toLowerCase()];
  if (capHit) {
    process.stdout.write(
      JSON.stringify({ ...capHit, kind: 'capability', matched_via: 'name' }) + '\n'
    );
    return;
  }

  // ─── Pass 4: capability alias lookup (normalized) ─────────────────────
  const capCanonical = capabilityAliasMap[normKey];
  if (capCanonical) {
    const hit = capabilities[capCanonical];
    if (hit) {
      const matchedViaName = normalize(capCanonical) === normKey;
      const output = {
        ...hit,
        kind: 'capability',
        matched_via: matchedViaName ? 'name' : 'alias',
      };
      if (!matchedViaName) output.matched_alias = query;
      process.stdout.write(JSON.stringify(output) + '\n');
      return;
    }
  }

  // ─── Miss ─────────────────────────────────────────────────────────────
  fail(
    `No blueprint or capability named or aliased '${query}'. Run \`npm run generate:readmes\` if you just added it, or check spelling.`,
    1
  );
}

main();
