#!/usr/bin/env node

/**
 * generate-readmes.js
 *
 * Reads YAML blueprints and writes a concise, user-friendly Markdown summary
 * next to each one:
 *
 *   blueprints/{category}/{feature}.blueprint.yaml
 *   blueprints/{category}/{feature}.md          ← generated by this script
 *
 * These co-located .md files are a HUMAN-FIRST quick reference — different
 * from the Jekyll reference pages under docs/blueprints/ (which are dense
 * site documentation rendered by generate-docs.js). The goal: a developer
 * browsing the repo should be able to read any feature in ~30 seconds.
 *
 * AUTO-GENERATED — do not edit the output manually. Re-run:
 *   node scripts/generate-readmes.js                          # all blueprints
 *   node scripts/generate-readmes.js blueprints/auth/login.blueprint.yaml  # one
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, basename, dirname } from 'path';
import { glob } from 'glob';
import YAML from 'yaml';

const ROOT = dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1'));
const PROJECT_ROOT = join(ROOT, '..');
const REPO_SLUG = 'TheunsBarnardt/ai-fdl-kit';
const DOCS_BASE_URL = 'https://theunsbarnardt.github.io/ai-fdl-kit';

// ─── Helpers ────────────────────────────────────────────────

function titleCase(str) {
  if (!str) return '';
  return String(str)
    .replace(/[_-]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function oneLine(str) {
  if (typeof str !== 'string') return String(str ?? '');
  return str.replace(/\s+/g, ' ').trim();
}

function bullet(text) {
  return `- ${oneLine(text)}`;
}

// ─── Renderers ──────────────────────────────────────────────

function renderHeader(bp, relPath) {
  const title = titleCase(bp.feature);
  const desc = oneLine(bp.description || '');
  const category = titleCase(bp.category || '');
  const tags = (bp.tags || []).join(' · ');

  let md = `<!-- AUTO-GENERATED FROM ${basename(relPath)} — DO NOT EDIT. Run \`npm run generate:readmes\` to refresh. -->\n\n`;
  md += `# ${title}\n\n`;
  if (desc) md += `> ${desc}\n\n`;
  md += `**Category:** ${category} · **Version:** ${bp.version || '—'}`;
  if (tags) md += ` · **Tags:** ${tags}`;
  md += `\n\n`;
  return md;
}

function renderWhatThisDoes(bp) {
  // A human-readable paragraph. Start from the description and add a short
  // intent sentence derived from the outcome names or flow names.
  const desc = oneLine(bp.description || '');
  const hasOutcomes = bp.outcomes && Object.keys(bp.outcomes).length > 0;
  const hasFlows = bp.flows && Object.keys(bp.flows).length > 0;

  let intent = '';
  if (hasOutcomes && hasFlows) {
    intent = `Combines technical outcomes (acceptance criteria) with documented business flows, so engineering and operations share one source of truth.`;
  } else if (hasOutcomes) {
    const count = Object.keys(bp.outcomes).length;
    intent = `Specifies ${count} acceptance outcome${count === 1 ? '' : 's'} that any implementation must satisfy, regardless of language or framework.`;
  } else if (hasFlows) {
    const count = Object.keys(bp.flows).length;
    intent = `Documents ${count} end-to-end business flow${count === 1 ? '' : 's'} as step-by-step procedures with actors and conditions.`;
  }

  if (!desc && !intent) return '';
  let md = `## What this does\n\n`;
  if (desc) md += `${desc}\n\n`;
  if (intent) md += `${intent}\n\n`;
  return md;
}

function renderFieldsBulleted(fields) {
  if (!fields || fields.length === 0) return '';
  let md = `## Fields\n\n`;
  for (const f of fields) {
    const req = f.required ? 'required' : 'optional';
    const label = f.label ? ` — ${oneLine(f.label)}` : '';
    md += `- **${f.name}** *(${f.type}, ${req})*${label}\n`;
  }
  return md + '\n';
}

function renderRulesFlat(rules) {
  if (!rules) return '';
  const lines = [];
  // Top-level keys become bold headers; string leaves become bullets
  // Handles both object-of-objects (key: description) and object-of-scalars
  const walk = (node, keyPath) => {
    if (node == null) return;
    // Scalar leaves (string, number, boolean) — emit directly
    if (typeof node !== 'object') {
      lines.push(`- **${keyPath.join(' → ')}:** ${oneLine(String(node))}`);
      return;
    }
    if (Array.isArray(node)) {
      // Render arrays of scalars as a single comma-joined line; recurse into
      // arrays of objects
      const scalars = node.filter((x) => x == null || typeof x !== 'object');
      const objects = node.filter((x) => x != null && typeof x === 'object' && !Array.isArray(x));
      if (scalars.length > 0) {
        lines.push(`- **${keyPath.join(' → ')}:** ${scalars.map((x) => String(x)).join(', ')}`);
      }
      for (const item of objects) walk(item, keyPath);
      return;
    }
    // Object — if it has a description field, treat that as a leaf, then walk siblings
    if (typeof node.description === 'string') {
      lines.push(`- **${keyPath.join(' → ')}:** ${oneLine(node.description)}`);
      for (const [k, v] of Object.entries(node)) {
        if (k === 'description') continue;
        walk(v, [...keyPath, k]);
      }
      return;
    }
    for (const [k, v] of Object.entries(node)) {
      walk(v, [...keyPath, k]);
    }
  };

  for (const [topKey, topVal] of Object.entries(rules)) {
    walk(topVal, [topKey]);
  }

  if (lines.length === 0) return '';
  return `## What must be true\n\n${lines.join('\n')}\n\n`;
}

function summarizeCondition(cond) {
  if (typeof cond === 'string') return oneLine(cond);
  if (!cond || typeof cond !== 'object') return String(cond);
  if (cond.description) return oneLine(cond.description);
  if (cond.any) return cond.any.map(summarizeCondition).join(' OR ');
  if (cond.all) return cond.all.map(summarizeCondition).join(' AND ');
  if (cond.field) {
    const op = cond.operator || 'eq';
    const val = cond.value !== undefined ? ` ${JSON.stringify(cond.value)}` : '';
    return `${cond.field} ${op}${val}`;
  }
  return '';
}

function summarizeAction(action) {
  if (typeof action === 'string') return oneLine(action);
  if (!action || typeof action !== 'object') return String(action);
  if (action.description) return oneLine(action.description);
  const name = action.action || 'do';
  if (name === 'transition_state') return `move ${action.field || 'status'} ${action.from || '?'} → ${action.to || '?'}`;
  if (name === 'emit_event') return `emit ${action.event}`;
  if (name === 'set_field') return `set ${action.target} = ${JSON.stringify(action.value)}`;
  if (name === 'notify') return `notify via ${action.channel || 'default'}`;
  if (name === 'call_service') return `call ${action.service || 'service'}`;
  return name;
}

function renderOutcomesProse(outcomes) {
  if (!outcomes || Object.keys(outcomes).length === 0) return '';

  const entries = Object.entries(outcomes).sort(
    (a, b) => (a[1]?.priority ?? 99) - (b[1]?.priority ?? 99)
  );

  const success = [];
  const failure = [];

  for (const [name, outcome] of entries) {
    if (!outcome || typeof outcome !== 'object') continue;
    const label = titleCase(name);

    const givenSummary = (outcome.given || [])
      .map(summarizeCondition)
      .filter(Boolean)
      .join('; ');

    const thenSummary = (outcome.then || [])
      .map(summarizeAction)
      .filter(Boolean)
      .join('; ');

    const result = outcome.result ? oneLine(outcome.result) : thenSummary;

    let sentence = `**${label}**`;
    if (givenSummary && result) {
      sentence += ` — when ${givenSummary}, then ${result}`;
    } else if (givenSummary) {
      sentence += ` — when ${givenSummary}`;
    } else if (result) {
      sentence += ` — ${result}`;
    }
    if (!sentence.endsWith('.')) sentence += '.';

    if (outcome.error) {
      sentence += ` *(error: \`${outcome.error}\`)*`;
      failure.push(`- ${sentence}`);
    } else {
      success.push(`- ${sentence}`);
    }
  }

  if (success.length === 0 && failure.length === 0) return '';

  let md = `## Success & failure scenarios\n\n`;
  if (success.length > 0) {
    md += `**✅ Success paths**\n\n`;
    md += success.join('\n') + '\n\n';
  }
  if (failure.length > 0) {
    md += `**❌ Failure paths**\n\n`;
    md += failure.join('\n') + '\n\n';
  }
  return md;
}

function renderFlowsProse(flows) {
  if (!flows || typeof flows !== 'object') return '';
  const entries = Object.entries(flows);
  if (entries.length === 0) return '';

  let md = `## Business flows\n\n`;
  for (const [name, flow] of entries) {
    if (!flow || typeof flow !== 'object') continue;
    md += `**${titleCase(name)}**`;
    if (flow.description) md += ` — ${oneLine(flow.description)}`;
    md += '\n\n';
    if (Array.isArray(flow.steps)) {
      for (const step of flow.steps) {
        const actor = step.actor ? ` *(${step.actor})*` : '';
        const label = step.action || step.id || 'step';
        const desc = step.description ? ` — ${oneLine(step.description)}` : '';
        md += `1. **${label}**${actor}${desc}\n`;
      }
      md += '\n';
    }
  }
  return md;
}

function renderErrorsList(errors) {
  if (!errors || errors.length === 0) return '';
  let md = `## Errors it can return\n\n`;
  for (const e of errors) {
    const msg = oneLine(e.message || '');
    md += `- \`${e.code}\` — ${msg}\n`;
  }
  return md + '\n';
}

function renderRelatedList(related) {
  if (!related || related.length === 0) return '';
  let md = `## Connects to\n\n`;
  for (const r of related) {
    const name = r.feature || r.name || '';
    const type = r.type ? ` *(${r.type})*` : '';
    const reason = r.reason ? ` — ${oneLine(r.reason)}` : '';
    md += `- **${name}**${type}${reason}\n`;
  }
  return md + '\n';
}

function renderFooter(bp, category) {
  const yamlFile = `${bp.feature}.blueprint.yaml`;
  const siteUrl = `${DOCS_BASE_URL}/blueprints/${category}/${bp.feature}/`;
  let md = `---\n\n`;
  md += `**Full reference:** [docs site](${siteUrl}) · **Spec source:** [\`${yamlFile}\`](./${yamlFile})\n\n`;
  md += `*Generated from YAML — any edits to this file will be overwritten. Update the blueprint YAML and re-run \`npm run generate:readmes\`.*\n`;
  return md;
}

// ─── Render a single blueprint ──────────────────────────────

function renderBlueprint(bp, relPath) {
  const category = bp.category || basename(dirname(relPath));
  let md = '';
  md += renderHeader(bp, relPath);
  md += renderWhatThisDoes(bp);
  md += renderFieldsBulleted(bp.fields);
  md += renderRulesFlat(bp.rules);
  md += renderOutcomesProse(bp.outcomes);
  md += renderFlowsProse(bp.flows);
  md += renderErrorsList(bp.errors);
  md += renderRelatedList(bp.related);
  md += renderFooter(bp, category);
  return md;
}

// ─── Index builder ──────────────────────────────────────────

function renderIndex(entries) {
  // entries: [{ bp, relFile }]
  const byCategory = {};
  for (const { bp, relFile } of entries) {
    const cat = bp.category || basename(dirname(relFile));
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push({ bp, relFile });
  }

  const total = entries.length;
  const categories = Object.keys(byCategory).sort();

  let md = `<!-- AUTO-GENERATED by scripts/generate-readmes.js — DO NOT EDIT. Regenerate with \`npm run generate:readmes\`. -->\n\n`;
  md += `# Blueprint Index\n\n`;
  md += `Fast lookup for all **${total}** blueprints across **${categories.length}** categories.\n`;
  md += `Each entry links to the human-friendly summary (\`.md\`) and the underlying spec (\`.blueprint.yaml\`).\n\n`;

  // Compact category nav
  md += `**Jump to a category:** `;
  md += categories
    .map((c) => `[${titleCase(c)}](#${c.toLowerCase()}) (${byCategory[c].length})`)
    .join(' · ');
  md += `\n\n---\n\n`;

  // Per-category sections
  for (const cat of categories) {
    const items = byCategory[cat].sort((a, b) => a.bp.feature.localeCompare(b.bp.feature));
    md += `## ${titleCase(cat)}\n\n`;
    md += `| Feature | Description | Version | Spec |\n`;
    md += `|---------|-------------|---------|------|\n`;
    for (const { bp } of items) {
      const desc = oneLine(bp.description || '').replace(/\|/g, '\\|');
      const feature = bp.feature;
      const mdLink = `./${cat}/${feature}.md`;
      const yamlLink = `./${cat}/${feature}.blueprint.yaml`;
      md += `| [**${feature}**](${mdLink}) | ${desc} | ${bp.version || '—'} | [yaml](${yamlLink}) |\n`;
    }
    md += `\n`;
  }

  md += `---\n\n`;
  md += `*Generated from YAML — any edits to this file will be overwritten. Update a blueprint and re-run \`npm run generate:readmes\`.*\n`;
  return md;
}

// ─── Main ───────────────────────────────────────────────────

function parseBlueprint(relFile) {
  const abs = join(PROJECT_ROOT, relFile);
  const raw = readFileSync(abs, 'utf8');
  let bp;
  try {
    bp = YAML.parse(raw);
  } catch (err) {
    throw new Error(`Failed to parse ${relFile}: ${err.message}`);
  }
  if (!bp || !bp.feature) {
    throw new Error(`${relFile} is missing \`feature\` — cannot generate readme`);
  }
  return { bp, abs };
}

async function processFile(relFile) {
  const { bp, abs } = parseBlueprint(relFile);
  const md = renderBlueprint(bp, relFile);
  const outPath = abs.replace(/\.blueprint\.yaml$/, '.md');
  writeFileSync(outPath, md);
  return { bp, outPath };
}

async function rebuildIndex() {
  const files = await glob('blueprints/**/*.blueprint.yaml', { cwd: PROJECT_ROOT });
  const entries = files.map((relFile) => {
    const { bp } = parseBlueprint(relFile);
    return { bp, relFile };
  });
  const indexPath = join(PROJECT_ROOT, 'blueprints', 'INDEX.md');
  writeFileSync(indexPath, renderIndex(entries));
  return indexPath;
}

async function main() {
  const arg = process.argv[2];

  if (arg) {
    // Single-file mode — accepts absolute or project-relative path
    const rel = arg.replace(PROJECT_ROOT + '\\', '').replace(PROJECT_ROOT + '/', '').replace(/\\/g, '/');
    if (!rel.endsWith('.blueprint.yaml')) {
      console.error(`Expected a *.blueprint.yaml path, got: ${arg}`);
      process.exit(1);
    }
    const { outPath } = await processFile(rel);
    console.log(`Wrote ${outPath}`);
    // Always rebuild the index so single-file edits keep it in sync
    const idx = await rebuildIndex();
    console.log(`Refreshed ${idx}`);
    return;
  }

  const files = await glob('blueprints/**/*.blueprint.yaml', { cwd: PROJECT_ROOT });
  console.log(`Found ${files.length} blueprints`);
  let count = 0;
  for (const file of files) {
    await processFile(file);
    count++;
  }
  const idx = await rebuildIndex();
  console.log(`Generated ${count} co-located readmes`);
  console.log(`Wrote index at ${idx}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
