#!/usr/bin/env node

/**
 * generate-readmes.js
 *
 * Reads YAML blueprints and writes a concise, user-friendly Markdown summary
 * next to each one:
 *
 *   blueprints/{category}/{feature}.blueprint.yaml
 *   blueprints/{category}/{feature}.md          ← generated by this script
 *
 * These co-located .md files are a HUMAN-FIRST quick reference — different
 * from the Jekyll reference pages under docs/blueprints/ (which are dense
 * site documentation rendered by generate-docs.js). The goal: a developer
 * browsing the repo should be able to read any feature in ~30 seconds.
 *
 * AUTO-GENERATED — do not edit the output manually. Re-run:
 *   node scripts/generate-readmes.js                          # all blueprints
 *   node scripts/generate-readmes.js blueprints/auth/login.blueprint.yaml  # one
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, basename, dirname } from 'path';
import { glob } from 'glob';
import YAML from 'yaml';
import { scoreBlueprint as scoreFitness } from './fitness.js';

const ROOT = dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1'));
const PROJECT_ROOT = join(ROOT, '..');
const REPO_SLUG = 'TheunsBarnardt/ai-fdl-kit';
const DOCS_BASE_URL = 'https://theunsbarnardt.github.io/ai-fdl-kit';

// ─── Load fitness data ──────────────────────────────────────
// Optional — if .fitness-changelog.json and .fitness-baseline.json exist,
// the readme includes a "Quality fitness" section showing the current score
// and (if applicable) what the auto-improver changed.

const CHANGELOG_PATH = join(PROJECT_ROOT, '.fitness-changelog.json');
const BASELINE_PATH = join(PROJECT_ROOT, '.fitness-baseline.json');
const CHANGELOG = existsSync(CHANGELOG_PATH)
  ? JSON.parse(readFileSync(CHANGELOG_PATH, 'utf-8'))
  : null;
const BASELINE = existsSync(BASELINE_PATH)
  ? JSON.parse(readFileSync(BASELINE_PATH, 'utf-8'))
  : null;
const BASELINE_MAP = BASELINE
  ? new Map((BASELINE.results || []).map((r) => [r.file, r.percent]))
  : null;

// scoreFitness = scoreBlueprint imported from ./fitness.js — single source of truth.

function fitnessBadge(percent) {
  if (percent >= 90) return '🟢';
  if (percent >= 75) return '🟢';
  if (percent >= 60) return '🟡';
  return '🔴';
}

// ─── Helpers ────────────────────────────────────────────────

function titleCase(str) {
  if (!str) return '';
  return String(str)
    .replace(/[_-]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function oneLine(str) {
  if (typeof str !== 'string') return String(str ?? '');
  return str.replace(/\s+/g, ' ').trim();
}

function bullet(text) {
  return `- ${oneLine(text)}`;
}

// Normalize an alias for deterministic lookup: lowercase, trim, and strip
// all separator characters (space, hyphen, underscore). Keeps "Sign In",
// "sign-in", "sign_in", and "signin" collapsing to the same key.
// MUST stay in sync with the normalize() in scripts/blueprint-lookup.js.
function normalizeAlias(s) {
  return String(s).toLowerCase().trim().replace(/[\s\-_]+/g, '');
}

// ─── Renderers ──────────────────────────────────────────────

function renderHeader(bp, relPath) {
  const title = titleCase(bp.feature);
  const desc = oneLine(bp.description || '');
  const category = titleCase(bp.category || '');
  const tags = (bp.tags || []).join(' · ');

  let md = `<!-- AUTO-GENERATED FROM ${basename(relPath)} — DO NOT EDIT. Run \`npm run generate:readmes\` to refresh. -->\n\n`;
  md += `# ${title}\n\n`;
  if (desc) md += `> ${desc}\n\n`;
  md += `**Category:** ${category} · **Version:** ${bp.version || '—'}`;
  if (tags) md += ` · **Tags:** ${tags}`;
  md += `\n\n`;
  return md;
}

function renderWhatThisDoes(bp) {
  // A human-readable paragraph. Start from the description and add a short
  // intent sentence derived from the outcome names or flow names.
  const desc = oneLine(bp.description || '');
  const hasOutcomes = bp.outcomes && Object.keys(bp.outcomes).length > 0;
  const hasFlows = bp.flows && Object.keys(bp.flows).length > 0;

  let intent = '';
  if (hasOutcomes && hasFlows) {
    intent = `Combines technical outcomes (acceptance criteria) with documented business flows, so engineering and operations share one source of truth.`;
  } else if (hasOutcomes) {
    const count = Object.keys(bp.outcomes).length;
    intent = `Specifies ${count} acceptance outcome${count === 1 ? '' : 's'} that any implementation must satisfy, regardless of language or framework.`;
  } else if (hasFlows) {
    const count = Object.keys(bp.flows).length;
    intent = `Documents ${count} end-to-end business flow${count === 1 ? '' : 's'} as step-by-step procedures with actors and conditions.`;
  }

  if (!desc && !intent) return '';
  let md = `## What this does\n\n`;
  if (desc) md += `${desc}\n\n`;
  if (intent) md += `${intent}\n\n`;
  return md;
}

function renderFieldsBulleted(fields) {
  if (!fields || fields.length === 0) return '';
  let md = `## Fields\n\n`;
  for (const f of fields) {
    const req = f.required ? 'required' : 'optional';
    const label = f.label ? ` — ${oneLine(f.label)}` : '';
    md += `- **${f.name}** *(${f.type}, ${req})*${label}\n`;
  }
  return md + '\n';
}

function renderRulesFlat(rules) {
  if (!rules) return '';
  const lines = [];
  // Top-level keys become bold headers; string leaves become bullets
  // Handles both object-of-objects (key: description) and object-of-scalars
  const walk = (node, keyPath) => {
    if (node == null) return;
    // Scalar leaves (string, number, boolean) — emit directly
    if (typeof node !== 'object') {
      lines.push(`- **${keyPath.join(' → ')}:** ${oneLine(String(node))}`);
      return;
    }
    if (Array.isArray(node)) {
      // Render arrays of scalars as a single comma-joined line; recurse into
      // arrays of objects
      const scalars = node.filter((x) => x == null || typeof x !== 'object');
      const objects = node.filter((x) => x != null && typeof x === 'object' && !Array.isArray(x));
      if (scalars.length > 0) {
        lines.push(`- **${keyPath.join(' → ')}:** ${scalars.map((x) => String(x)).join(', ')}`);
      }
      for (const item of objects) walk(item, keyPath);
      return;
    }
    // Object — if it has a description field, treat that as a leaf, then walk siblings
    if (typeof node.description === 'string') {
      lines.push(`- **${keyPath.join(' → ')}:** ${oneLine(node.description)}`);
      for (const [k, v] of Object.entries(node)) {
        if (k === 'description') continue;
        walk(v, [...keyPath, k]);
      }
      return;
    }
    for (const [k, v] of Object.entries(node)) {
      walk(v, [...keyPath, k]);
    }
  };

  for (const [topKey, topVal] of Object.entries(rules)) {
    walk(topVal, [topKey]);
  }

  if (lines.length === 0) return '';
  return `## What must be true\n\n${lines.join('\n')}\n\n`;
}

function summarizeCondition(cond) {
  if (typeof cond === 'string') return oneLine(cond);
  if (!cond || typeof cond !== 'object') return String(cond);
  if (cond.description) return oneLine(cond.description);
  if (cond.any) return cond.any.map(summarizeCondition).join(' OR ');
  if (cond.all) return cond.all.map(summarizeCondition).join(' AND ');
  if (cond.field) {
    const op = cond.operator || 'eq';
    const val = cond.value !== undefined ? ` ${JSON.stringify(cond.value)}` : '';
    return `${cond.field} ${op}${val}`;
  }
  return '';
}

function summarizeAction(action) {
  if (typeof action === 'string') return oneLine(action);
  if (!action || typeof action !== 'object') return String(action);
  if (action.description) return oneLine(action.description);
  const name = action.action || 'do';
  if (name === 'transition_state') return `move ${action.field || 'status'} ${action.from || '?'} → ${action.to || '?'}`;
  if (name === 'emit_event') return `emit ${action.event}`;
  if (name === 'set_field') return `set ${action.target} = ${JSON.stringify(action.value)}`;
  if (name === 'notify') return `notify via ${action.channel || 'default'}`;
  if (name === 'call_service') return `call ${action.service || 'service'}`;
  return name;
}

function renderOutcomesProse(outcomes) {
  if (!outcomes || Object.keys(outcomes).length === 0) return '';

  const entries = Object.entries(outcomes).sort(
    (a, b) => (a[1]?.priority ?? 99) - (b[1]?.priority ?? 99)
  );

  const success = [];
  const failure = [];

  for (const [name, outcome] of entries) {
    if (!outcome || typeof outcome !== 'object') continue;
    const label = titleCase(name);

    const givenSummary = (outcome.given || [])
      .map(summarizeCondition)
      .filter(Boolean)
      .join('; ');

    const thenSummary = (outcome.then || [])
      .map(summarizeAction)
      .filter(Boolean)
      .join('; ');

    const result = outcome.result ? oneLine(outcome.result) : thenSummary;

    let sentence = `**${label}**`;
    if (givenSummary && result) {
      sentence += ` — when ${givenSummary}, then ${result}`;
    } else if (givenSummary) {
      sentence += ` — when ${givenSummary}`;
    } else if (result) {
      sentence += ` — ${result}`;
    }
    if (!sentence.endsWith('.')) sentence += '.';

    if (outcome.description) {
      sentence += ` _Why: ${oneLine(outcome.description).replace(/\.$/, '')}._`;
    }

    if (outcome.error) {
      sentence += ` *(error: \`${outcome.error}\`)*`;
      failure.push(`- ${sentence}`);
    } else {
      success.push(`- ${sentence}`);
    }
  }

  if (success.length === 0 && failure.length === 0) return '';

  let md = `## Success & failure scenarios\n\n`;
  if (success.length > 0) {
    md += `**✅ Success paths**\n\n`;
    md += success.join('\n') + '\n\n';
  }
  if (failure.length > 0) {
    md += `**❌ Failure paths**\n\n`;
    md += failure.join('\n') + '\n\n';
  }
  return md;
}

function renderFlowsProse(flows) {
  if (!flows || typeof flows !== 'object') return '';
  const entries = Object.entries(flows);
  if (entries.length === 0) return '';

  let md = `## Business flows\n\n`;
  for (const [name, flow] of entries) {
    if (!flow || typeof flow !== 'object') continue;
    md += `**${titleCase(name)}**`;
    if (flow.description) md += ` — ${oneLine(flow.description)}`;
    md += '\n\n';
    if (Array.isArray(flow.steps)) {
      for (const step of flow.steps) {
        const actor = step.actor ? ` *(${step.actor})*` : '';
        const label = step.action || step.id || 'step';
        const desc = step.description ? ` — ${oneLine(step.description)}` : '';
        md += `1. **${label}**${actor}${desc}\n`;
      }
      md += '\n';
    }
  }
  return md;
}

function renderErrorsList(errors) {
  if (!errors || errors.length === 0) return '';
  let md = `## Errors it can return\n\n`;
  for (const e of errors) {
    const msg = oneLine(e.message || '');
    md += `- \`${e.code}\` — ${msg}\n`;
  }
  return md + '\n';
}

function renderRelatedList(related) {
  if (!related || related.length === 0) return '';
  let md = `## Connects to\n\n`;
  for (const r of related) {
    const name = r.feature || r.name || '';
    const type = r.type ? ` *(${r.type})*` : '';
    const reason = r.reason ? ` — ${oneLine(r.reason)}` : '';
    md += `- **${name}**${type}${reason}\n`;
  }
  return md + '\n';
}

function renderFitness(bp, relPath) {
  const fit = scoreFitness(bp);
  const badge = fitnessBadge(fit.percent);
  const normPath = relPath.replace(/\\/g, '/');

  // Per-dimension rows: only show the ones that matter (skip full-credit ones
  // for optional sections to keep the section compact)
  const labels = {
    description: 'Description',
    rules: 'Rules',
    outcomes: 'Outcomes',
    structure: 'Structured conditions',
    error_binding: 'Error binding',
    fields: 'Field validation',
    relationships: 'Relationships',
    events: 'Events',
    agi: 'AGI readiness',
    simplicity: 'Simplicity',
  };

  const rows = Object.entries(fit.dims).map(([key, d]) => {
    const pct = Math.round((d.score / d.max) * 100);
    const bar = '█'.repeat(Math.round(d.score)) + '░'.repeat(d.max - Math.round(d.score));
    return `| ${labels[key]} | \`${bar}\` | ${d.score}/${d.max} |`;
  });

  let md = `## Quality fitness ${badge} ${fit.percent}/100\n\n`;
  md += `Automated quality score measuring outcome coverage, rule structure, error binding, and field validation depth. `;
  md += `Regenerated by \`npm run fitness\` — see [\`scripts/fitness.js\`](../../scripts/fitness.js) for the scoring model.\n\n`;
  md += `| Dimension | Score | Points |\n`;
  md += `|-----------|-------|--------|\n`;
  md += rows.join('\n') + '\n\n';

  // Baseline delta (from saved baseline)
  if (BASELINE_MAP) {
    const baselineScore = BASELINE_MAP.get(normPath);
    if (typeof baselineScore === 'number' && baselineScore !== fit.percent) {
      const delta = fit.percent - baselineScore;
      const sign = delta >= 0 ? '+' : '';
      const trend = delta > 0 ? '📈' : delta < 0 ? '📉' : '➡️';
      md += `${trend} **${sign}${delta}** since baseline (${baselineScore} → ${fit.percent})\n\n`;
    }
  }

  // Auto-improver transformations
  const logEntry = CHANGELOG?.entries?.[normPath];
  if (logEntry && Array.isArray(logEntry.transformations) && logEntry.transformations.length > 0) {
    md += `**Recent auto-improvements** *(via autoresearch-style keep-or-reset loop — applied only because they raised the fitness score)*\n\n`;
    for (const t of logEntry.transformations) {
      md += `- \`${t.id}\` **${t.name || ''}** — ${t.note}\n`;
    }
    md += `\n`;
  }

  return md;
}

function renderEvents(events) {
  if (!Array.isArray(events) || events.length === 0) return '';
  let md = '## Events\n\n';
  for (const event of events) {
    if (!event || !event.name) continue;
    md += `**\`${event.name}\`**`;
    if (event.description) md += ` — ${event.description}`;
    md += '\n';
    // Prefer payload_schema (typed) over payload (plain array)
    if (Array.isArray(event.payload_schema) && event.payload_schema.length > 0) {
      md += '\n| Field | Type | Source |\n|-------|------|--------|\n';
      for (const p of event.payload_schema) {
        md += `| \`${p.field}\` | ${p.type} | ${p.source} |\n`;
      }
      md += '\n';
    } else if (Array.isArray(event.payload) && event.payload.length > 0) {
      md += `  Payload: \`${event.payload.join('`, `')}\`\n`;
    }
    md += '\n';
  }
  return md;
}

function renderFooter(bp, category) {
  const yamlFile = `${bp.feature}.blueprint.yaml`;
  const siteUrl = `${DOCS_BASE_URL}/blueprints/${category}/${bp.feature}/`;
  let md = `---\n\n`;
  md += `**Full reference:** [docs site](${siteUrl}) · **Spec source:** [\`${yamlFile}\`](./${yamlFile})\n\n`;
  md += `*Generated from YAML — any edits to this file will be overwritten. Update the blueprint YAML and re-run \`npm run generate:readmes\`.*\n`;
  return md;
}

// ─── Render a single blueprint ──────────────────────────────

function renderBlueprint(bp, relPath) {
  const category = bp.category || basename(dirname(relPath));
  let md = '';
  md += renderHeader(bp, relPath);
  md += renderWhatThisDoes(bp);
  md += renderFieldsBulleted(bp.fields);
  md += renderRulesFlat(bp.rules);
  md += renderOutcomesProse(bp.outcomes);
  md += renderFlowsProse(bp.flows);
  md += renderErrorsList(bp.errors);
  md += renderEvents(bp.events);
  md += renderRelatedList(bp.related);
  md += renderFitness(bp, relPath);
  md += renderFooter(bp, category);
  return md;
}

// ─── Index builder ──────────────────────────────────────────

function renderIndex(entries) {
  // entries: [{ bp, relFile }]
  const byCategory = {};
  for (const { bp, relFile } of entries) {
    const cat = bp.category || basename(dirname(relFile));
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push({ bp, relFile });
  }

  const total = entries.length;
  const categories = Object.keys(byCategory).sort();

  let md = `<!-- AUTO-GENERATED by scripts/generate-readmes.js — DO NOT EDIT. Regenerate with \`npm run generate:readmes\`. -->\n\n`;
  md += `# Blueprint Index\n\n`;
  md += `Fast lookup for all **${total}** blueprints across **${categories.length}** categories.\n`;
  md += `Each entry links to the human-friendly summary (\`.md\`) and the underlying spec (\`.blueprint.yaml\`).\n\n`;

  // Compact category nav
  md += `**Jump to a category:** `;
  md += categories
    .map((c) => `[${titleCase(c)}](#${c.toLowerCase()}) (${byCategory[c].length})`)
    .join(' · ');
  md += `\n\n---\n\n`;

  // Per-category sections
  for (const cat of categories) {
    const items = byCategory[cat].sort((a, b) => a.bp.feature.localeCompare(b.bp.feature));
    md += `## ${titleCase(cat)}\n\n`;
    md += `| Feature | Description | Version | Spec |\n`;
    md += `|---------|-------------|---------|------|\n`;
    for (const { bp } of items) {
      const desc = oneLine(bp.description || '').replace(/\|/g, '\\|');
      const feature = bp.feature;
      const mdLink = `./${cat}/${feature}.md`;
      const yamlLink = `./${cat}/${feature}.blueprint.yaml`;
      // Appended aliases make the INDEX grep-able by human-typed phrases
      // (e.g. `grep -i "sign in"` finds the login row). The alias hint is
      // rendered as a subdued trailing clause inside the description cell
      // so the existing 4-column table format is preserved and the lookup
      // regex in scripts/blueprint-lookup.js keeps working unchanged.
      const aliases = Array.isArray(bp.aliases) ? bp.aliases : [];
      const aliasSuffix = aliases.length
        ? ` <sub>_aka_ ${aliases.map((a) => String(a).replace(/\|/g, '\\|')).join(', ')}</sub>`
        : '';
      md += `| [**${feature}**](${mdLink}) | ${desc}${aliasSuffix} | ${bp.version || '—'} | [yaml](${yamlLink}) |\n`;
    }
    md += `\n`;
  }

  md += `---\n\n`;
  md += `*Generated from YAML — any edits to this file will be overwritten. Update a blueprint and re-run \`npm run generate:readmes\`.*\n`;
  return md;
}

// ─── Main ───────────────────────────────────────────────────

function parseBlueprint(relFile) {
  const abs = join(PROJECT_ROOT, relFile);
  const raw = readFileSync(abs, 'utf8');
  let bp;
  try {
    bp = YAML.parse(raw);
  } catch (err) {
    throw new Error(`Failed to parse ${relFile}: ${err.message}`);
  }
  if (!bp || !bp.feature) {
    throw new Error(`${relFile} is missing \`feature\` — cannot generate readme`);
  }
  return { bp, abs };
}

async function processFile(relFile) {
  const { bp, abs } = parseBlueprint(relFile);
  const md = renderBlueprint(bp, relFile);
  const outPath = abs.replace(/\.blueprint\.yaml$/, '.md');
  writeFileSync(outPath, md);
  return { bp, outPath };
}

async function rebuildIndex() {
  const files = await glob('blueprints/**/*.blueprint.yaml', { cwd: PROJECT_ROOT });
  const entries = files.map((relFile) => {
    const { bp } = parseBlueprint(relFile);
    return { bp, relFile };
  });
  // Capability blueprints live alongside features but use a different file
  // suffix and a different schema — collect them separately so the JSON
  // index exposes { features, capabilities } as distinct namespaces.
  const capabilityFiles = await glob('blueprints/capabilities/**/*.capability.yaml', {
    cwd: PROJECT_ROOT,
  });
  const capabilityEntries = capabilityFiles.map((relFile) => {
    const abs = join(PROJECT_ROOT, relFile);
    const raw = readFileSync(abs, 'utf8');
    let cap;
    try {
      cap = YAML.parse(raw);
    } catch (err) {
      throw new Error(`Failed to parse ${relFile}: ${err.message}`);
    }
    if (!cap || !cap.capability) {
      throw new Error(`${relFile} is missing \`capability\` — cannot index`);
    }
    return { cap, relFile };
  });

  const indexPath = join(PROJECT_ROOT, 'blueprints', 'INDEX.md');
  writeFileSync(indexPath, renderIndex(entries));
  // Emit the programmatic index alongside the human-readable INDEX.md.
  // blueprint-index.json is what scripts/blueprint-lookup.js consumes —
  // INDEX.md is for humans only. YAML remains the source of truth; this
  // JSON is just a fast-loading projection of it.
  const blueprintIndexPath = rebuildBlueprintIndex(entries, capabilityEntries);
  return { indexPath, blueprintIndexPath };
}

/**
 * Build the programmatic blueprint index from YAML. Single-file view of
 * every blueprint's lookup-relevant metadata, plus a normalized-alias →
 * canonical-feature-name map for O(1) alias resolution.
 *
 * Consumed exclusively by scripts/blueprint-lookup.js. Humans should read
 * blueprints/INDEX.md instead; no script should parse INDEX.md.
 *
 * Collisions (same alias claimed by two blueprints) are surfaced as a
 * warning here — the hard check lives in scripts/validate.js. We pick the
 * first occurrence so we never emit a half-built index.
 */
function rebuildBlueprintIndex(entries, capabilityEntries = []) {
  const features = {};
  const capabilities = {};
  const aliasMap = {};
  const collisions = [];

  for (const { bp, relFile } of entries) {
    const feature = bp.feature;
    if (!feature) continue;

    const category = bp.category || basename(dirname(relFile));
    const relNorm = relFile.replace(/\\/g, '/');
    const mdPath = relNorm.replace(/\.blueprint\.yaml$/, '.md');
    const aliases = Array.isArray(bp.aliases) ? bp.aliases : [];
    const uses = Array.isArray(bp.uses) ? bp.uses : [];

    features[feature] = {
      feature,
      category,
      yaml_path: relNorm,
      md_path: mdPath,
      version: bp.version || '',
      description: bp.description || '',
      aliases,
      uses,
    };

    // Index both the canonical name and the aliases under their normalized
    // forms so "Login", "LOGIN", "sign in", "sign-in" all resolve in O(1).
    const claimable = [feature, ...aliases];
    for (const raw of claimable) {
      const key = normalizeAlias(raw);
      if (!key) continue;
      if (aliasMap[key] && aliasMap[key] !== feature) {
        collisions.push({ alias: raw, normalized: key, first: aliasMap[key], second: feature });
        continue;
      }
      aliasMap[key] = feature;
    }
  }

  // Index capabilities into a separate namespace. Keep their alias map
  // distinct from the feature alias_map so a feature and a capability can
  // share a name (or alias) without colliding in the lookup surface.
  // blueprint-lookup.js checks features first, then capabilities.
  const capabilityAliasMap = {};
  for (const { cap, relFile } of capabilityEntries) {
    const id = cap.capability;
    if (!id) continue;

    const relNorm = relFile.replace(/\\/g, '/');
    const aliases = Array.isArray(cap.aliases) ? cap.aliases : [];
    const targets = cap.implementations ? Object.keys(cap.implementations) : [];

    capabilities[id] = {
      capability: id,
      kind: cap.kind || '',
      stability: cap.stability || 'stable',
      yaml_path: relNorm,
      version: cap.version || '',
      description: cap.description || '',
      aliases,
      targets,
    };

    const claimable = [id, ...aliases];
    for (const raw of claimable) {
      const key = normalizeAlias(raw);
      if (!key) continue;
      if (capabilityAliasMap[key] && capabilityAliasMap[key] !== id) {
        collisions.push({
          alias: raw,
          normalized: key,
          first: `capability ${capabilityAliasMap[key]}`,
          second: `capability ${id}`,
        });
        continue;
      }
      capabilityAliasMap[key] = id;
    }
  }

  if (collisions.length > 0) {
    console.warn(
      `blueprint-index: ${collisions.length} alias collision(s) detected — keeping first claim. Validator will fail these:`
    );
    for (const c of collisions) {
      console.warn(`  "${c.alias}" (norm: "${c.normalized}") claimed by "${c.first}" and "${c.second}"`);
    }
  }

  const blueprintIndexPath = join(PROJECT_ROOT, 'blueprints', 'blueprint-index.json');
  writeFileSync(
    blueprintIndexPath,
    JSON.stringify(
      {
        _generated_by: 'scripts/generate-readmes.js',
        _note:
          'Programmatic blueprint index — consumed by scripts/blueprint-lookup.js. ' +
          'YAML blueprints remain the source of truth; this JSON is a fast-loading ' +
          'projection. Never hand-edit. INDEX.md is the human-readable view.',
        generated_at: new Date().toISOString(),
        feature_count: Object.keys(features).length,
        capability_count: Object.keys(capabilities).length,
        features,
        capabilities,
        alias_map: aliasMap,
        capability_alias_map: capabilityAliasMap,
      },
      null,
      2
    ) + '\n'
  );
  return blueprintIndexPath;
}

async function main() {
  const arg = process.argv[2];

  if (arg) {
    // Single-file mode — accepts absolute or project-relative path
    const rel = arg.replace(PROJECT_ROOT + '\\', '').replace(PROJECT_ROOT + '/', '').replace(/\\/g, '/');
    if (!rel.endsWith('.blueprint.yaml')) {
      console.error(`Expected a *.blueprint.yaml path, got: ${arg}`);
      process.exit(1);
    }
    const { outPath } = await processFile(rel);
    console.log(`Wrote ${outPath}`);
    // Always rebuild both the human INDEX.md and the programmatic
    // blueprint-index.json so single-file edits keep both in sync.
    const { indexPath, blueprintIndexPath } = await rebuildIndex();
    console.log(`Refreshed ${indexPath}`);
    console.log(`Refreshed ${blueprintIndexPath}`);
    return;
  }

  const files = await glob('blueprints/**/*.blueprint.yaml', { cwd: PROJECT_ROOT });
  console.log(`Found ${files.length} blueprints`);
  let count = 0;
  for (const file of files) {
    await processFile(file);
    count++;
  }
  const { indexPath, blueprintIndexPath } = await rebuildIndex();
  console.log(`Generated ${count} co-located readmes`);
  console.log(`Wrote human index at ${indexPath}`);
  console.log(`Wrote programmatic index at ${blueprintIndexPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
